---
name: CI
"on":
  push:
    branches: [main]
    tags: [v*]
  pull_request: null
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - uses: pre-commit/action@v3.0.1
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.8, 3.12]
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Installation (deps and package)
        # we install with flit --pth-file,
        # so that coverage will be recorded for the module
        run: |
          pipx install flit
          flit install --deps=production --extras=test --pth-file
      - name: Run pytest
        run: |
          pytest --cov=$(ls | grep "mdformat_" | head) --cov-report=xml --cov-report=term-missing
      # - name: Upload to Codecov
      #   if: matrix.os == 'ubuntu-latest' && matrix.python-version == 3.12
      #   uses: codecov/codecov-action@v1
      #   with:
      #     name: pytests-py3.12
      #     flags: pytests
      #     file: ./coverage.xml
      #     fail_ci_if_error: true
  pre-commit-hook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Installation (deps and package)
        run: |
          pipx install pre-commit
          pip install .
      - name: run pre-commit with plugin
        run: |
          pre-commit run --config .pre-commit-test.yaml --all-files --verbose --show-diff-on-failure
  publish:
    name: Publish to PyPi
    needs: [pre-commit, tests, pre-commit-hook]
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
    runs-on: ubuntu-latest
    # Fix 403 error (https://github.com/softprops/action-gh-release/issues/400)
    permissions:
      contents: write
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: install flit
        run: |
          pipx install flit~=3.0
      - name: Build and publish
        run: |
          flit publish
        env:
          FLIT_USERNAME: __token__
          FLIT_PASSWORD: ${{ secrets.PYPI_KEY }}
      - name: Generate GitHub Release Notes
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
